spring.application.name=PMP
server.port=8082


spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.sqysojnauglgdskzxigc
spring.datasource.password=Q8QK8fRdiHTtNKkQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=xqq0CeyGUmH6cVylurvmF+T0wZFrJI8AoJs3B5znqqY=
jwt.expiration=86400000

supabase.url=https://sqysojnauglgdskzxigc.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeXNvam5hdWdsZ2Rza3p4aWdjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDExNTA2OCwiZXhwIjoyMDg5NjkxMDY4fQ.5mNKPZD61l5wcIEBRr80VmOb4tF_w9UHHUhNhU6yWck
supabase.bucket=pmpBucket

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

cors.allowed-origins=http://localhost:5173